task:
  timeout_in: 120m
  env:
    CIRRUS_WORKING_DIR: /usr/local/src
    SOURCE: /usr/local/src/
    GS_AUTH: ENCRYPTED[c4b5b0404f5bfdc1b663a1eb5b70f3187b5d470d02eec3265b06b8e0d30226781523630931c1da6db06714c0d359f71f]
    PATH: /root/.cargo/bin:$PATH:$SOURCE/gcloud/google-cloud-sdk/bin
    SHELL: /bin/bash
  container:
    dockerfile: Dockerfile
    # image: ubuntu
    cpu: 8
    memory: 24
  name: linux
  # install_deps_script: apt-get update && apt-get install -y wget python clang llvm git curl
  install_gcloud_script: ./scripts/install_gcloud.sh
  check_gcloud_script:
    - echo "REVISION: $(git rev-parse HEAD)"
    - gsutil cp FIREFOX_SHA gs://juggler-builds/$(git rev-parse HEAD)/
  clone_firefox_script: ./scripts/fetch_firefox.sh
  apply_patches_script:
    - cd $SOURCE/firefox
    - git config --global user.name "cirrus-ci-builder"
    - git config --global user.email "aslushnikov@gmail.com"
    - git am ../patches/*
    - ln -s $PWD/../juggler testing/juggler
  bootstrap_firefox_script:
    - cd $SOURCE/firefox
    - ./mach bootstrap --application-choice=browser --no-interactive
  build_firefox_script:
    - cd $SOURCE/firefox
    - ./mach build
  package_firefox_script:
    - cd $SOURCE/firefox
    - ./mach package
  upload_build_to_gcloud_script:
    - bash $SOURCE/scripts/upload_linux.sh

